### ISSUE TITLE
Still same problem, with cloudlaunch

### ISSUE THREAD

**Issue by elettod** [galaxyproject/cloudlaunch#212] opened 2020-08-11 10:01 UTC
Cloudlaunch has the AdministratorAccess policy, now.
After a while, the instance tries to start and configure itself, I get the same message.

UNABLE TO CHECK STATUS
Health check failed: CloudBridgeBaseException: Unable to locate credentials from exception type: <class 'botocore.exceptions.NoCredentialsError'>

**Comment by almahmoud** [comment] 2020-08-11 16:11
This is not the same error as the one indicating insufficient permissions.
This is due to the fact that you are using temporary credentials rather than saving credentials to your profile. In this case, CloudLaunch does not keep a copy of your credentials after the initial launch, meaning it doesn’t have the necessary credentials to check on the status of the instance. Note that the instance most likely did get booted, so remember to terminate them from the AWS console or you may incur unnecessary costs.
If you want to not have this error post-launch, you will have to give CloudLaunch the right to store your credentials (by saving them to your profile), in which case the status of the machine can be checked from the CloudLaunch page.

**Comment by almahmoud** [comment] 2020-08-11 16:15
Closing this as a duplicate of https://github.com/galaxyproject/cloudlaunch/issues/207 . Please reopen if it seems like there is another issue

**Closed by almahmoud** 2020-08-11 16:15 UTC
