### ISSUE TITLE
Get error launching galaxy 18.05 to east-us-1

### ISSUE THREAD

**Issue by phyjoekim** [galaxyproject/cloudlaunch#173] opened 2019-06-20 22:23 UTC
Everytime i try East-US-1 i get this error. i tried launching to other areas for example AWS ap-southeast-2 and it worked fine.
Not sure how to get around this error. 
FAILURE Create appliance task failed: CloudBridgeBaseException: An error occurred (InvalidParameter) when calling the RunInstances operation: Security group sg-0ac4bfad8799dc296 and subnet subnet-09f54e424be711304 belong to different networks. from exception type: <class 'botocore.exceptions.ClientError'>
--

**Comment by afgane** [comment] 2019-06-24 11:45
Until we publish a fix for this issue and update the live server, you should be able to access the AWS console at https://console.aws.amazon.com/vpc/home?region=us-east-1#subnets:sort=SubnetId and delete subnet `subnet-09f54e424be711304`. While logged into the console, perhaps best to also delete security group `sg-0ac4bfad8799dc296` from https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#SecurityGroups:sort=groupId. Once that's done, try launching again and suitable replacements should be created.

**Comment by phyjoekim** [comment] 2019-06-24 16:29
Thank you, this resolved the issue. I had to delete the subnet, internet gateway and security group, but this fixed the issue.

**Comment by afgane** [comment] 2019-06-24 16:33
Glad to hear that. We can leave this open for the time being to track the issue but may end up moving to to the [CloudBridge repo](https://github.com/CloudVE/cloudbridge) where this error originates.

**Comment by phyjoekim** [comment] 2019-06-24 16:50
Not sure if your reply email is monitored. But maybe you can help. So because I couldn’t get 18.05 launched, I launched 17.05.  And tried upgrading to 19.05. I downloaded it and installed the new version. But after reboots and starting galaxy it still shows 17.05. What step am I missing?

Best regards,
Joe Kim

**Comment by phyjoekim** [comment] 2019-06-24 16:52
I meant 17.09 not 17.05

Best regards,
Joe Kim

From: Joe Kim
Sent: Monday, June 24, 2019 9:50 AM
To: galaxyproject/cloudlaunch <reply@reply.github.com>
Subject: RE: [galaxyproject/cloudlaunch] Get error launching galaxy 18.05 to east-us-1 (#173)

Not sure if your reply email is monitored. But maybe you can help. So because I couldn’t get 18.05 launched, I launched 17.05.  And tried upgrading to 19.05. I downloaded it and installed the new version. But after reboots and starting galaxy it still shows 17.05. What step am I missing?

Best regards,
Joe Kim

**Comment by phyjoekim** [comment] 2019-06-24 16:54
Sorry, I double checked it is 17.05 you the old galaxy cloudman launch page.

Best regards,
Joe Kim

From: Joe Kim
Sent: Monday, June 24, 2019 9:52 AM
To: galaxyproject/cloudlaunch <reply@reply.github.com>
Subject: RE: [galaxyproject/cloudlaunch] Get error launching galaxy 18.05 to east-us-1 (#173)

I meant 17.09 not 17.05

Best regards,
Joe Kim

From: Joe Kim
Sent: Monday, June 24, 2019 9:50 AM
To: galaxyproject/cloudlaunch <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: RE: [galaxyproject/cloudlaunch] Get error launching galaxy 18.05 to east-us-1 (#173)

Not sure if your reply email is monitored. But maybe you can help. So because I couldn’t get 18.05 launched, I launched 17.05.  And tried upgrading to 19.05. I downloaded it and installed the new version. But after reboots and starting galaxy it still shows 17.05. What step am I missing?

Best regards,
Joe Kim

**Comment by afgane** [comment] 2019-06-24 23:17
Upgrades under GVL/CloudMan are unfortunately not simple. There are a lot of dependencies on how the overall system is built to enable semi-autonomous operation and hence a simple update to Galaxy tends not to work, particularly when doing such a large jump across versions. To do the update, it'll require some [understanding of the overall system](https://galaxyproject.org/cloudman/building/), and then experimenting with the [upgrade process](https://github.com/galaxyproject/galaxy-cloudman-playbook/#building-or-updating-galaxyfs) to sync it to the latest Galaxy version requirements. 

We are working on an all-new system and for deploying, managing, and upgrading Galaxy that will include the latest version of the system. You can launch an instance of it from here: https://launch.usegalaxy.org/catalog/appliance/cloudman-20 but please know what it is in pre-alpha state without any real data persistence and no documentation. However, we are working on it daily so hoping for a release in not too distant future.

**Comment by phyjoekim** [comment] 2019-06-24 23:41
Thanks you for your help. I will try out the new version you sent.

Best regards,
Joe Kim

**Comment by phyjoekim** [comment] 2019-06-25 03:11
Hi I was able to install, but I get this login page. Where do I go to setup an account.

[cid:image001.png@01D52AC8.ED98D660]

Best regards,
Joe Kim

**Comment by afgane** [comment] 2019-06-25 12:44
The username is `admin` and the password is whatever you supplied during launch. Galaxy will be available under `<instance_ip_address/galaxy/` URI (note the trailing slash as it's required).

**Comment by phyjoekim** [comment] 2019-06-26 00:20
Hi Enis,

I did get 19.05 installed and I am in the galaxy webpage.
I edited the galaxy.yml and added the admin: joekim@phytelligence.com<mailto:joekim@phytelligence.com> and rebooted the AWS server.
But I don’t see the admin tab.  In previous versions, I also added went to the ipaddress\cloud and there was a admin button that I added the emails. I don’t see this anymore.
Any idea how to do this?

Best regards,
Joe Kim

**Comment by afgane** [comment] 2019-06-26 20:46
Making yourself an admin is done via the CloudMan application running at `https://<instance_ip_address>`. Once there, you can see an checkbox-like icon next to the galaxy application access url. If you click that, an editor should show up with `galaxy.yml` being available in one of the tabs. If you add the `admin_users` line there, and click save, it should work as soon as the Galaxy process starts up (which will happen automatically and will take a few minutes).

**Comment by phyjoekim** [comment] 2019-06-26 21:06
Got it all working, thank you.

Thanks,
Joe Kim

________________________________

**Comment by phyjoekim** [comment] 2019-06-26 21:56
Hi one thing to note, when you launch this on AWS, if you choose the general options it auto generates the keypair and you cant download it afterwards.
Also the version that deploys doesn’t have the username logins enabled for putty, have to attach the keypair which you don’t have.
The other version I was able to login via ssh with ubuntu, but its disabled, so no way in.

I have to rebuild again and specify a keypair I already have downloaded.

Best regards,
Joe Kim

**Comment by afgane** [comment] 2019-06-27 13:38
That's largely by design. Auto-enabling password-based ssh on an instance was something we had received complaints before as not being the best security practice. With the new deployment model, everything runs in containers and the plan is to expose the container control services using best-practice methods (e.g., APIs, Dashboard, in-broswer terminal) and enable controlled changes to the environment instead of ad-hoc file edits. 
Having said that, what is your use case for needing to ssh into the instance?

**Comment by phyjoekim** [comment] 2019-06-27 20:02
Main case would be that if you use the default launch page and you don’t choose the advanced configuration, the deployment will auto create the keypair and you have no chance to download the key. So you will be locked out of SSH to server.

I am also getting this error now, when I try to  upload a larger file it gives this warning and start over again and again, never download the files.
I increased the drive space to 1500gb in case I was running of space.
[cid:image001.png@01D52CE8.8182B780]
Best regards,
Joe Kim

**Closed** 2019-11-06 05:20 UTC
