### ISSUE TITLE
Error launching any instance type

### ISSUE THREAD

**Issue by bioboot** [galaxyproject/cloudlaunch#233] opened 2020-11-18 19:43 UTC
Using CloudLaunch website I get:

FAILURECreate appliance task failed: CloudBridgeBaseException: An error occurred (InvalidInstanceID.NotFound) when calling the CreateTags operation: The instance ID 'i-056318f101ed1b3fe' does not exist from exception type: <class 'botocore.exceptions.ClientError'> Report this failure?

I now get this when trying to launch any instance type:
Appliance: Genomics Virtual Lab (GVL)Version: GVL 4.4.0 (Galaxy 18.05)
Cloud: Amazon Web Services

or 
Appliance: Genomics Virtual Lab (GVL)Version: GVL 4.4.0 (Galaxy 18.05)
Cloud: Amazon Web Services

Any suggestions? Thank you

**Comment by nuwang** [comment] 2020-11-19 10:56
@bioboot I can confirm that we've been experiencing this issue as well, since maybe 2 days ago. It seems to be related to some AWS concurrency issues, presumably due to some changes on their end. Some code that would be expected to work is no longer working. We are trying to work around this, see here for the tracking issue: https://github.com/CloudVE/cloudbridge/pull/257

**Comment by nuwang** [comment] 2020-12-02 13:45
@bioboot This should be fixed now. Let us know if you encounter a recurrence.

**Closed by nuwang** 2020-12-02 13:45 UTC
