### ISSUE TITLE
Error in launching Galaxy Cloudman

### ISSUE THREAD

**Issue by mdash84** [galaxyproject/cloudlaunch#131] opened 2017-12-26 17:40 UTC
Hi,
I am facing some error message while launching galaxy cloudman using AWS credentials. The credentials were accepted but in the final page when I include the password and storage details as mentioned in the "Getting Started" page, I run into some sort of long error message and in the end displaying:  **Make sure that the selected options are a valid combination of settings. Press the Previous button to go back and make changes**. 
I don't understand the above error message except that it looks like the options I am filling are not correct. Below is the screenshots for 1) Launch credentials: the details filled and 2) the error message received. 
1) ![launch credentials](https://user-images.githubusercontent.com/34852226/34361539-fcf5b066-ea90-11e7-8121-630c68a3b5f5.png)
2) ![error message](https://user-images.githubusercontent.com/34852226/34361571-45f8d9fa-ea91-11e7-9a63-d8b2819699a2.png)

Please let me know if I am filling some wrong options and if yes, then where am I going wrong. 

Thanks,
M Dash

**Comment by nuwang** [comment] 2017-12-26 18:40
@mdash84 Thanks very much for reporting this and sorry about the setback. The error was caused by two issues back to back. The first was the one I mentioned in gitter "Your account is currently being verified." which is temporary. However, the second one in the screen shot above was caused because we updated the server a few hours ago, and this had caused a breakage. This has now been fixed.

You may also have run into the following issue: "Your requested instance type (c3.large) is not supported in your requested Availability Zone (us-east-1a). Please retry your request by not specifying an Availability Zone or choosing us-east-1c, us-east-1b, us-east-1d, us-east-1e."

So you may need to choose a different instance type or zone to get the launch to work correctly. 

Finally, if you want the latest version of Galaxy (17.09), you will need to launch the GVL 4.3.0 appliance from the catalog. We have not yet updated the docs to reflect this.

Please keep us posted on how you go and we'd be happy to help if you run into any more issues.

**Comment by mdash84** [comment] 2017-12-27 07:17
@nuwang Thanks a lot for your reply. I followed your instruction. When I do not specify any availability zone, I get the same error message as before. On changing the availability zone to us-east-1c, it started launching but then I got a message "FAILURE Launch task time limit exceeded; stopping the task."
Is it still an account or server problem or shall I try with other options of zone? 

![launch failure](https://user-images.githubusercontent.com/34852226/34373902-072729fc-eb04-11e7-83b4-25144c7aec64.png)

**Comment by nuwang** [comment] 2017-12-27 07:31
@mdash84 I just tried launching a few new instances and they seemed to launch correctly without any issues. The settings I used were: Galaxy Cloudman 16.10 with c3.large instance type. I selected a disk size of 20GB. I didn't select a placement zone and left the defaults as is.

Could you try this configuration and let me know whether it works ok?

**Comment by mdash84** [comment] 2017-12-27 10:49
@nuwang I tried your setting and I am getting the error message "Your requested instance type (c3.large) is not supported in your requested Availability Zone (us-east-1a)". If I don't make any changes to the zone (see image 2), then by default it is using us-east-1a. If I specify different zone (see image 3), then it is taking a long time to launch eventually failing to launch. Could these issues be location specific? I am trying to launch from India. Or could you detect some error in the settings that I am missing. 

![page 1](https://user-images.githubusercontent.com/34852226/34379497-84141e26-eb21-11e7-8c6e-65f6f9076b43.png)

![page 2](https://user-images.githubusercontent.com/34852226/34379507-8f6dd974-eb21-11e7-8617-3f7807b2393f.png)

![page 2 zone change](https://user-images.githubusercontent.com/34852226/34379516-97fbc7e0-eb21-11e7-8c12-9457e83fa3ad.png)

**Comment by nuwang** [comment] 2017-12-27 12:34
@mdash84 Thanks for the detailed report - it was very useful to isolate the problem. I think I know where the issue is now - there's a problem with routing traffic to the instance. I'm working on a fix now and will keep you posted.

**Comment by mdash84** [comment] 2017-12-28 05:38
@nuwang Great I look forward to it.

**Comment by nuwang** [comment] 2017-12-28 07:42
@mdash84 I believe the issue should have been fixed with this commit: https://github.com/galaxyproject/cloudlaunch/commit/4c1975364926abe0a8be37280cc16985e394b6dd

Please try now and let us know if you run into any more issues.

**Comment by mdash84** [comment] 2017-12-28 09:46
@nuwang It worked!!! Thank you so much for your help and consistent effort.

**Comment by nuwang** [comment] 2017-12-28 18:52
@mdash84 That's great news - thanks for all the testing and feedback!

**Closed by nuwang** 2017-12-28 18:52 UTC
