### ISSUE TITLE
Galaxy in GVL out-f-the-box issue

### ISSUE THREAD

**Issue by martenson** [galaxyproject/cloudlaunch#140] opened 2018-03-24 21:31 UTC
> I gave GVL a try and was initially impressed by the interface and excited to use the latest release of Galaxy; however, after getting it set up, I immediately encountered an error "right out of the box". The Cluster info log is reporting over and over the following error:

`R_COMM channel basic get exception: [Errno 32] Broken pipe`

as reported here: https://biostar.usegalaxy.org/p/27235/#27271

**Comment by nuwang** [comment] 2018-03-25 13:15
Thanks for reporting this. Initially, we thought that this was a firewall issue, and indeed, there was a slight misconfiguration in the firewall, but that hasn't fixed the problem. It's a rabbitmq comms issue, but why it's being triggered is not clear. Still looking into this and will report back.

**Comment by martenson** [comment] 2018-03-26 13:53
xref http://dev.list.galaxyproject.org/GVL-Galaxy-ver-18-01-instance-error-R-COMM-channel-basic-get-exception-Errno-32-Broken-pipe-td4671328.html

**Comment by afgane** [comment] 2018-03-26 20:02
This should be fixed now. The launcher has been updated to use a new image and newly launched instances seem to work fine. The root cause was an auto-upgrade of some packages that in turn broke the message queue so that update been explicitly disabled now.

I'll close this for now and we can reopen if the issue resurfaces.

**Closed by afgane** 2018-03-26 20:02 UTC

**Comment by Slugger70** [comment] 2018-08-02 04:42
What was the fix @afgane? Is there a way to revert the changes so that Rabbit works again? I'm experiencing the same issue on a machine that I don't want to kill
