### ISSUE TITLE
CloudLaunch V2 failure to launch galaxxy 18.05

### ISSUE THREAD

**Issue by udaydd** [galaxyproject/cloudlaunch#160] opened 2018-10-26 05:03 UTC
FAILURE 
Create appliance task time limit exceeded; stopping the task.

**Comment by nuwang** [comment] 2018-10-26 05:33
@udaydd I just tried launching two instances on AWS and NeCTAR but didn't run into the issue. Can you give us more details about what settings you changed, if any, and what the message was before the time limit was exceeded? Did it get to the stage where it says:
```
Waiting for application to become ready at http://<ip_address>/
```
Also, more details such as which cloud you launched, which application/version and any other relevant settings would be useful.

**Comment by udaydd** [comment] 2018-10-26 06:16
Thank you for your response. Yes I got the message while installing on AWS with m5 large cluster with 4 CPU. Waiting for application to become ready at http://<ip_address>/ but at the end it is reporting failure. Let me please know your AWS specifications and configuration I will use the same and try once again. Best
    On Friday, 26 October, 2018, 11:03:16 AM IST, Nuwan Goonasekera <notifications@github.com> wrote:  
 
 
@udaydd I just tried launching two instances on AWS and NeCTAR but didn't run into the issue. Can you give us more details about what settings you changed, if any, and what the message was before the time limit was exceeded? Did it get to the stage where it says:
Waiting for application to become ready at http://<ip_address>/

Also, more details such as which cloud you launched, which application/version and any other relevant settings would be useful.

**Comment by nuwang** [comment] 2018-10-26 07:30
In the meantime, you may have to manually delete the instance that was created through the AWS console.

**Comment by udaydd** [comment] 2018-10-26 12:16
Nuwan,I new to Galaxy launch on AWS using CloudLaunch. Could you please give me detailed steps to do it properly? I have been trying hard without success with the same time out error.Best,Uday
    On Friday, 26 October, 2018, 1:00:56 PM IST, Nuwan Goonasekera <notifications@github.com> wrote:  
 
 
In the meantime, you may have to manually delete the instance that was created through the AWS console.

**Comment by nuwang** [comment] 2018-10-26 12:19
@udaydd We are updating the server at the moment, and the fix should be ready in a few minutes. I'll message you here when done.

To delete your existing instance, please login to the AWS dashboard: https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Instances:sort=publicIp
You will see your instances there. Right click on the instance, and selecting "instance state" -> terminate, and that should remove the instance permanently.

**Comment by nuwang** [comment] 2018-10-26 12:29
@udaydd We've just completed the update. Please give it a go and let us know whether it looks ok.

**Comment by udaydd** [comment] 2018-10-26 16:08
Still I continue to get same error  like belowFAILURE 
Create appliance task time limit exceeded; stopping the task.

I am not sure  where is the problem? 

    On Friday, 26 October, 2018, 6:19:41 PM IST, Nuwan Goonasekera <notifications@github.com> wrote:  
 
 
Reopened #160.

**Comment by nuwang** [comment] 2018-10-26 18:31
@udaydd Could you login to the AWS console, and check whether the instance has a public IP assigned to it? If so, can you try accessing the public IP directly and see whether that works.

If you cannot access by IP (which if my hunch is correct, you should not be able to), could you go to VPCs->Route table in the AWS Console here: https://console.aws.amazon.com/vpc/home?region=us-east-1#routetables:

Could you post a screenshot of your route table as shown below?
![image](https://user-images.githubusercontent.com/2070605/47585607-6300c600-d97b-11e8-8518-0e7726a2e8e5.png)

**Comment by nuwang** [comment] 2018-10-26 19:44
@udaydd We found one more minor issue which has now been fixed. The issue is that some of these conditions are difficult to trigger depending on existing networking setups, but we think it's all good now. Let us know how it goes.

**Comment by udaydd** [comment] 2018-10-27 08:05
Thank you Nuwan for all the help. Yes I could successfully launch GVL today on AWS. But when I open galaxy portal web address bar shows Not secure site. What is the issue now?
Regards,Uday
    On Friday, 26 October, 2018, 6:19:41 PM IST, Nuwan Goonasekera <notifications@github.com> wrote:  
 
 
Reopened #160.

**Comment by nuwang** [comment] 2018-10-27 08:15
@udaydd I'm glad to hear it's working. The reason you see "not secure", is because https is not enabled by default. This is normal and can be safely ignored (unless you are dealing with highly sensitive information, in which case you can enable https through some admin options).

**Closed** 2018-10-27 08:15 UTC

**Comment by udaydd** [comment] 2018-10-27 08:20
Thank you for all help and cooperation
    On Saturday, 27 October, 2018, 1:45:41 PM IST, Nuwan Goonasekera <notifications@github.com> wrote:  
 
 
@udaydd I'm glad to hear it's working. The reason you see "not secure", is because https is not enabled by default. This is normal and can be safely ignored (unless you are dealing with highly sensitive information, in which case you can enable https through some admin options).
