### ISSUE TITLE
GCP Appliance Launch Failure

### ISSUE THREAD

**Issue by kdbinder** [galaxyproject/cloudlaunch#180] opened 2019-11-05 18:26 UTC
Upon creating the appliance (post successful VPC creation), Cloud Launch fails showing:

It appears the API call is not formatted correctly

FAILURE
Create appliance task failed: CloudBridgeBaseException: <HttpError 400 when requesting https://compute.googleapis.com/compute/v1/projects/<PROJECT_ID>/global/networks/https%3A%2F%2Fwww.googleapis.com%2Fcompute%2Fv1%2Fprojects%2F<PROJECT_ID>%2Fglobal%2Fnetworks%2Fcloudbridge-net-fdc370?alt=json returned "Invalid value 'https://www.googleapis.com/compute/v1/projects/<PROJECT _ID>/global/networks/cloudbridge-net-fdc370'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'"> from exception type: <class 'googleapiclient.errors.HttpError'>`

**Comment by nuwang** [comment] 2019-11-06 05:22
@kdbinder Thanks for reporting this. @almahmoud is working on a fix and we'll keep this issue updated as we go along.

**Comment by nuwang** [comment] 2019-11-19 18:41
@kdbinder This has been fixed in: https://github.com/CloudVE/cloudbridge/pull/229
It's a bit puzzling because it seems to have been caused by a change in the GCP platform, and there's a mismatch between the url provided by the discovery endpoint and the url used by the resource (e.g. the discovery endpoint returns `https://compute.googleapis.com/` whereas the resource url is `https://www.googleapis.com/compute`. We've made the code more generic to handle this difference, but the "more exact" approach would have been to respect the discovery endpoint information I think.
Please try launching a new instance now and let us know if you encounter any issues. I'll close this for now.

**Closed by nuwang** 2019-11-19 18:41 UTC
